import type { Framework, Project, ProjectFile } from './types';
export const frameworks: Framework[] = ['Auto-select', 'LangGraph', 'CrewAI', 'OpenAI Agents', 'Lyzr', 'Custom'];
export const templates = [
  {id:'research',name:'Research copilot',category:'Research',description:'Turn a topic into a sourced brief, with a researcher and a critical reviewer.',prompt:'Build a research copilot that researches a topic, checks sources, and writes a concise brief.',icon:'Search',color:'lavender',framework:'LangGraph' as Framework},
  {id:'support',name:'Customer support agent',category:'Customer experience',description:'Find the right answers in your knowledge base. Hand off when a human can help.',prompt:'Build a customer support agent with a knowledge base, ticket triage, and a human handoff.',icon:'Headphones',color:'mint',framework:'Lyzr' as Framework},
  {id:'sales',name:'Sales intelligence',category:'Sales & marketing',description:'Research accounts, qualify opportunities, and prepare your next conversation.',prompt:'Build a sales intelligence app that researches companies and qualifies inbound leads.',icon:'Target',color:'peach',framework:'CrewAI' as Framework},
  {id:'content',name:'Content studio',category:'Sales & marketing',description:'Go from one idea to a considered first draft, with an editor in the loop.',prompt:'Build a content studio with a writer agent, an editor, and a content approval queue.',icon:'PenTool',color:'blue',framework:'OpenAI Agents' as Framework},
  {id:'ops',name:'Operations analyst',category:'Operations',description:'Connect business data and turn recurring questions into clear, useful answers.',prompt:'Build an operations analyst that explores business data and summarizes key changes.',icon:'ChartNoAxesCombined',color:'yellow',framework:'LangGraph' as Framework},
  {id:'recruiting',name:'Hiring assistant',category:'Operations',description:'Organize applications and interview notes, with hiring decisions left to people.',prompt:'Build a hiring assistant that organizes applications and interview notes for human review.',icon:'Users',color:'rose',framework:'Custom' as Framework},
];
export const connectors = [
  {name:'Slack',letter:'#',color:'#633369',category:'Communication',description:'Bring conversations and agent notifications into your team’s channels.',scopes:['Read selected channels','Post messages with approval']},
  {name:'Notion',letter:'N',color:'#242823',category:'Knowledge',description:'Give your agents context from your workspace documentation.',scopes:['Read selected pages','Create pages with approval']},
  {name:'Google Drive',letter:'△',color:'#35886c',category:'Knowledge',description:'Find answers across the documents your team already uses.',scopes:['Read selected files only']},
  {name:'GitHub',letter:'⌘',color:'#252b34',category:'Development',description:'Let an agent look up issues and repository context.',scopes:['Read selected repositories','Create issues with approval']},
  {name:'HubSpot',letter:'H',color:'#f27650',category:'CRM',description:'Ground your sales workflows in customer and deal context.',scopes:['Read contacts and deals','Update records with approval']},
  {name:'Gmail',letter:'M',color:'#cd594c',category:'Communication',description:'Draft helpful replies with a person approving every send.',scopes:['Read selected threads','Create drafts only']},
  {name:'Linear',letter:'◩',color:'#6970c9',category:'Development',description:'Connect product issues to your everyday agent workflows.',scopes:['Read issues','Create issues with approval']},
  {name:'Teams',letter:'T',color:'#6264a7',category:'Communication',description:'Preview how team conversations could inform an agent workflow.',scopes:['Read selected conversations','Post messages with approval']},
  {name:'Telegram',letter:'T',color:'#419bc5',category:'Communication',description:'Explore a scoped messaging workflow with human review.',scopes:['Read selected chats','Send messages with approval']},
  {name:'X',letter:'X',color:'#30352f',category:'Communication',description:'Plan a social research and draft-post workflow.',scopes:['Read selected posts','Prepare post drafts','Publish with approval']},
  {name:'Asana',letter:'A',color:'#de7480',category:'Development',description:'Explore how project tasks could become useful agent context.',scopes:['Read selected projects and tasks','Update tasks with approval']},
  {name:'Dropbox',letter:'D',color:'#5181bc',category:'Knowledge',description:'Preview a file-based knowledge connection for selected folders.',scopes:['Read selected folders and files','Create files with approval']},
  {name:'Calendar',letter:'C',color:'#5b86bf',category:'Communication',description:'Plan scheduling assistance around a calendar you choose.',scopes:['Read selected calendars','Create events with approval']},
  {name:'Docs',letter:'D',color:'#5c82b2',category:'Knowledge',description:'Explore document context and reviewed writing assistance.',scopes:['Read selected documents','Update documents with approval']},
  {name:'Trello',letter:'T',color:'#5185b7',category:'Development',description:'Preview an agent workflow around boards, lists, and cards.',scopes:['Read selected boards','Create and update cards with approval']},
  {name:'Confluence',letter:'C',color:'#577fc4',category:'Knowledge',description:'Plan a knowledge connection to selected team spaces.',scopes:['Read selected spaces and pages','Create pages with approval']},
  {name:'Apollo',letter:'A',color:'#b89948',category:'CRM',description:'Explore account research and reviewed prospecting workflows.',scopes:['Read selected account context','Prepare outreach drafts','Update records with approval']},
  {name:'Excel',letter:'E',color:'#508163',category:'Knowledge',description:'Preview spreadsheet context and proposed workbook changes.',scopes:['Read selected workbooks','Update cells with approval']},
  {name:'Freshdesk',letter:'F',color:'#589b78',category:'CRM',description:'Plan ticket research and a human-reviewed support reply flow.',scopes:['Read selected tickets','Prepare reply drafts','Update tickets with approval']},
  {name:'Sheets',letter:'S',color:'#589b73',category:'Knowledge',description:'Explore a shared-spreadsheet workflow with explicit write boundaries.',scopes:['Read selected spreadsheets','Update rows with approval']},
  {name:'Jira',letter:'J',color:'#5f80ba',category:'Development',description:'Preview issue triage and reviewed project updates.',scopes:['Read selected projects and issues','Create and update issues with approval']},
  {name:'Custom MCP',letter:'↗',color:'#56866c',category:'Custom',description:'Describe a Model Context Protocol server to connect your own tools.',scopes:['Choose tools individually','Require approval for write tools']},
];
export function escapeHtml(value:string){return value.replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]!));}
export function previewHtml(title:string,description:string){
 return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box}body{margin:0;background:#f8faf9;color:#26372e;font:14px system-ui,sans-serif}header{display:flex;align-items:center;justify-content:space-between;padding:22px 30px;background:white;border-bottom:1px solid #e3eae5}.brand{font-weight:700;font-size:17px}.tag{font-size:11px;padding:5px 9px;border-radius:8px;background:#edf4ef;color:#528360}main{max-width:740px;margin:50px auto;padding:0 25px}h1{font-size:31px;letter-spacing:-1px;font-weight:550;margin:12px 0}p{line-height:1.65;color:#718078}small{color:#6f8d77;text-transform:uppercase;letter-spacing:2px;font-size:10px}.box{margin-top:27px;background:white;border:1px solid #e0e8e3;border-radius:16px;padding:20px;box-shadow:0 8px 30px #1e4c2a06}textarea{width:100%;min-height:94px;border:0;resize:vertical;font:14px system-ui;outline-color:#86c39c}button{background:#316d4b;color:white;padding:11px 17px;border:0;border-radius:8px;cursor:pointer}button:disabled{opacity:.6}.row{display:flex;align-items:center;justify-content:space-between;gap:12px}.help{font-size:11px;color:#9aaba0}#result{margin-top:20px;line-height:1.8;white-space:pre-wrap}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:25px}.card{border:1px solid #e4eae6;border-radius:12px;padding:18px;background:white}.card b{display:block;font-size:20px;margin-bottom:6px}.card span{font-size:11px;color:#7a8a80}@media(max-width:480px){.cards{grid-template-columns:1fr}main{margin-top:25px}header{padding:16px}h1{font-size:26px}}</style></head><body><header><span class="brand">✳ ${escapeHtml(title)}</span><span class="tag">Interactive sample</span></header><main><small>Your workspace, amplified</small><h1>A little help. A lot more possible.</h1><p>${escapeHtml(description)}</p><div class="box"><textarea id="request" aria-label="Ask your agent" placeholder="What would you like to work on?"></textarea><div class="row"><span class="help">Demo response · no model is called</span><button id="run">Get started ↗</button></div><div id="result" role="status"></div></div><div class="cards"><div class="card"><b>01</b><span>Share your goal</span></div><div class="card"><b>02</b><span>Review the agent’s work</span></div><div class="card"><b>03</b><span>Make it your own</span></div></div></main><script>document.getElementById('run').onclick=()=>{const input=document.getElementById('request');const result=document.getElementById('result');if(!input.value.trim()){result.textContent='Add a request to try the sample flow.';return}result.textContent='Sample result for: '+input.value+'\\n\\n1. Understand the request and collect relevant context.\\n2. Prepare a draft for your review.\\n3. Ask for approval before taking action.\\n\\nThis is an interactive prototype, not a live agent response.';};</script></body></html>`;
}
export function createProject(prompt:string, framework:Framework='Auto-select',title?:string,source:Project['source']='prompt',files?:ProjectFile[]):Project{
 const matching=templates.find(t=>prompt.toLowerCase().includes(t.id)||prompt.toLowerCase().includes(t.name.toLowerCase()));
 const name=title||matching?.name||prompt.replace(/^(build|create|make|design)\s+(me\s+)?(a|an)\s+/i,'').slice(0,45).replace(/^./,s=>s.toUpperCase());
 const chosen=framework==='Auto-select'?(matching?.framework||'LangGraph'):framework;
 const initialFiles=files?.length?files:[{path:'index.html',content:previewHtml(name,prompt.split('\n')[0].slice(0,400))},{path:'agents/main.py',content:`# ${name}\n# Illustrative ${chosen} scaffold. Not executed in this prototype.\n\nAGENT_CONFIG = {\n    "framework": ${JSON.stringify(chosen)},\n    "name": "Researcher",\n    "instructions": "Find relevant information and cite sources.",\n    "approval_required": True,\n}\n\ndef run(request):\n    raise NotImplementedError("Connect your model and tools to run this agent.")\n`},{path:'README.md',content:`# ${name}\n\n${prompt}\n\nFramework: ${chosen}\n\nThis is an Architect 2.0 prototype scaffold. index.html is an interactive sample. The agent code is illustrative and requires implementation and credentials before execution.\n`}];
 return {id:crypto.randomUUID(),title:name,description:prompt,framework:chosen,source,updatedAt:Date.now(),stage:'draft',color:matching?.color||'mint',state:{messages:[{id:crypto.randomUUID(),role:'user',text:prompt,time:new Date().toISOString()},{id:crypto.randomUUID(),role:'assistant',text:source==='import'?'Your files are ready to explore. Review the project structure, then tell me what you want to change. Analysis and build steps in this prototype are simulated.':`Here’s a starting point for ${name.toLowerCase()}. I’ve prepared an editable sample and a suggested agent setup. Review the plan, try the preview, and make it yours. Generation is simulated in this prototype.`,time:new Date().toISOString()}],files:initialFiles,agents:[{name:'Researcher',role:'Collect relevant context',model:'Model not connected',instructions:'Find relevant information, cite sources, and ask for missing context.'},{name:'Reviewer',role:'Check before delivery',model:'Model not connected',instructions:'Check the draft for accuracy. Request human approval before external actions.'}],connections:[],versions:[{id:crypto.randomUUID(),label:'Initial project',at:new Date().toISOString(),files:structuredClone(initialFiles)}],theme:'Sage'}};
}
export function seedProjects():Project[]{return [createProject(templates[0].prompt,'LangGraph','Research copilot','template'),createProject(templates[1].prompt,'Lyzr','Customer support','template'),createProject(templates[2].prompt,'CrewAI','Sales intelligence','template')].map((p,i)=>({...p,updatedAt:Date.now()-(i+1)*86400000,stage:i===0?'ready':'draft'}));}
export function relativeTime(value:number){const hours=Math.floor((Date.now()-value)/3600000);return hours<1?'Just now':hours<24?`${hours}h ago`:`${Math.floor(hours/24)}d ago`;}
